name: arle_app
description: App Arle


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.1.0-6.0.dev <4.0.0'







dependencies:
  flutter_native_splash: ^2.2.19
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ADD8E6"
  color_dark: "#201E1E"
  image: assets/images/splash/logo_arle.png
  image_dark: assets/images/splash/logo_arle.png

  android_12:
    image: assets/images/splash/logo_arle.png
    icon_background_color: "#ADD8E6"
    image_dark: assets/images/splash/logo_arle.png
    icon_background_color_dark: "#201E1E"




  flutter_lints: ^2.0.0





flutter:




  uses-material-design: true

  assets:
    - assets/images/welcome_image/
    - assets/images/login/